/*
AwayTeam: "Netherlands"
AwayTeamAccurateBackZonePass: "86"
AwayTeamAccurateChippedPass: "3"
AwayTeamAccurateCornersIntobox: "1"
AwayTeamAccurateCross: "1"
AwayTeamAccurateFlickOn: "1"
AwayTeamAccurateFwdZonePass: "70"
AwayTeamAccurateGoalKicks: "1"
AwayTeamAccurateKeeperThrows: "2"
AwayTeamAccurateLayoffs: "9"
AwayTeamAccurateLongBalls: "25"
AwayTeamAccuratePass: "155"
AwayTeamAccurateThroughBall: "1"
AwayTeamAccurateThrows: "8"
AwayTeamAerialLost: "5"
AwayTeamAerialWon: "5"
AwayTeamAttAssistOpenplay: "1"
AwayTeamAttAssistSetplay: "1"
AwayTeamAttBxCentre: "4"
AwayTeamAttHdTotal: "1"
AwayTeamAttIboxMiss: "1"
AwayTeamAttIboxTarget: "4"
AwayTeamAttMissHigh: "1"
AwayTeamAttMissHighLeft: "1"
AwayTeamAttMissHighRight: "1"
AwayTeamAttMissLeft: "1"
AwayTeamAttOboxBlocked: "1"
AwayTeamAttOboxGoal: "1"
AwayTeamAttOboxTarget: "1"
AwayTeamAttObxCentre: "1"
AwayTeamAttRfGoal: "1"
AwayTeamAttRfMiss: "1"
AwayTeamAttRfTarget: "3"
AwayTeamAttRfTotal: "2"
AwayTeamAttSbxCentre: "1"
AwayTeamAttSetpiece: "2"
AwayTeamAttSvLowCentre: "1"
AwayTeamAttSvLowRight: "2"
AwayTeamAttemptsConcededObox: "3"
AwayTeamBallRecovery: "12"
AwayTeamBlockedScoringAtt: "2"
AwayTeamChallengeLost: "6"
AwayTeamCrosses18yard: "6"
AwayTeamCrosses18yardplus: "1"
AwayTeamDuelLost: "27"
AwayTeamDuelWon: "23"
AwayTeamEffectiveClearance: "11"
AwayTeamEffectiveHeadClearance: "4"
AwayTeamFinalThirdEntries: "41"
AwayTeamFirstHalfGoals: "1"
AwayTeamFkFoulLost: "6"
AwayTeamFkFoulWon: "6"
AwayTeamFormationUsed: "4231"
AwayTeamForwardGoals: "1"
AwayTeamGoalAssist: "1"
AwayTeamGoalAssistIntentional: "4"
AwayTeamGoalAssistOpenplay: "1"
AwayTeamGoalKicks: "2"
AwayTeamGoals: "1"
AwayTeamGoalsConceded: "1"
AwayTeamGoalsConcededObox: "1"
AwayTeamHeadClearance: "7"
AwayTeamInterception: "8"
AwayTeamKeeperThrows: "2"
AwayTeamLongPassOwnToOpp: "49"
AwayTeamLongPassOwnToOppSuccess: "24"
AwayTeamLostCorners: "1"
AwayTeamOfftargetAttAssist: "4"
AwayTeamOntargetAttAssist: "2"
AwayTeamOntargetScoringAtt: "1"
AwayTeamOutfielderBlock: "2"
AwayTeamPassesLeft: "37"
AwayTeamPassesRight: "17"
AwayTeamPossessionPercentage: "56.9"
AwayTeamSavedObox: "1"
AwayTeamScore: "1"
AwayTeamShieldBallOop: "1"
AwayTeamShotOffTarget: "1"
AwayTeamSubsMade: "3"
AwayTeamTotalAttAssist: "2"
AwayTeamTotalBackZonePass: "97"
AwayTeamTotalChippedPass: "10"
AwayTeamTotalClearance: "15"
AwayTeamTotalContest: "12"
AwayTeamTotalCornersIntobox: "2"
AwayTeamTotalCross: "10"
AwayTeamTotalCrossNocorner: "8"
AwayTeamTotalFlickOn: "4"
AwayTeamTotalFwdZonePass: "113"
AwayTeamTotalLaunches: "17"
AwayTeamTotalLayoffs: "10"
AwayTeamTotalLongBalls: "38"
AwayTeamTotalPass: "200"
AwayTeamTotalScoringAtt: "4"
AwayTeamTotalTackle: "5"
AwayTeamTotalThroughBall: "1"
AwayTeamTotalThrows: "11"
AwayTeamTotalYelCard: "1"
AwayTeamTouches: "301"
AwayTeamWonCorners: "2"
AwayTeamWonTackle: "5"
HomeTeam: "Uruguay"
HomeTeamAccurateBackZonePass: "57"
HomeTeamAccurateChippedPass: "5"
HomeTeamAccurateCross: "1"
HomeTeamAccurateFlickOn: "2"
HomeTeamAccurateFwdZonePass: "50"
HomeTeamAccurateGoalKicks: "1"
HomeTeamAccurateKeeperThrows: "3"
HomeTeamAccurateLayoffs: "8"
HomeTeamAccurateLongBalls: "10"
HomeTeamAccuratePass: "106"
HomeTeamAccurateThroughBall: "1"
HomeTeamAccurateThrows: "10"
HomeTeamAerialLost: "5"
HomeTeamAerialWon: "5"
HomeTeamAttAssistOpenplay: "3"
HomeTeamAttBxCentre: "1"
HomeTeamAttHdMiss: "1"
HomeTeamAttHdTotal: "1"
HomeTeamAttIboxMiss: "1"
HomeTeamAttIboxTarget: "3"
HomeTeamAttLgCentre: "1"
HomeTeamAttMissHigh: "1"
HomeTeamAttMissHighLeft: "1"
HomeTeamAttMissHighRight: "3"
HomeTeamAttMissLeft: "1"
HomeTeamAttOboxBlocked: "2"
HomeTeamAttOboxGoal: "1"
HomeTeamAttOboxTarget: "1"
HomeTeamAttObxCentre: "2"
HomeTeamAttRfMiss: "1"
HomeTeamAttRfTarget: "3"
HomeTeamAttRfTotal: "6"
HomeTeamAttSetpiece: "1"
HomeTeamAttSvLowCentre: "1"
HomeTeamAttSvLowRight: "1"
HomeTeamAttemptsConcededObox: "2"
HomeTeamBallRecovery: "14"
HomeTeamBlockedScoringAtt: "2"
HomeTeamChallengeLost: "7"
HomeTeamCrosses18yard: "5"
HomeTeamCrosses18yardplus: "1"
HomeTeamDuelLost: "23"
HomeTeamDuelWon: "27"
HomeTeamEffectiveClearance: "7"
HomeTeamEffectiveHeadClearance: "3"
HomeTeamFinalThirdEntries: "25"
HomeTeamFirstHalfGoals: "1"
HomeTeamFkFoulLost: "7"
HomeTeamFkFoulWon: "5"
HomeTeamFormationUsed: "442"
HomeTeamForwardGoals: "1"
HomeTeamGoalAssist: "1"
HomeTeamGoalAssistOpenplay: "1"
HomeTeamGoalKicks: "1"
HomeTeamGoals: "1"
HomeTeamGoalsConceded: "1"
HomeTeamGoalsConcededObox: "1"
HomeTeamHeadClearance: "7"
HomeTeamInterception: "9"
HomeTeamKeeperThrows: "3"
HomeTeamLongPassOwnToOpp: "26"
HomeTeamLongPassOwnToOppSuccess: "12"
HomeTeamLostCorners: "2"
HomeTeamOfftargetAttAssist: "2"
HomeTeamOntargetAttAssist: "2"
HomeTeamOntargetScoringAtt: "2"
HomeTeamOutfielderBlock: "1"
HomeTeamPassesLeft: "26"
HomeTeamPassesRight: "22"
HomeTeamPossessionPercentage: "43.1"
HomeTeamSavedObox: "1"
HomeTeamScore: "1"
HomeTeamShotOffTarget: "2"
HomeTeamSubsMade: "3"
HomeTeamTotalAttAssist: "4"
HomeTeamTotalBackZonePass: "70"
HomeTeamTotalChippedPass: "12"
HomeTeamTotalClearance: "12"
HomeTeamTotalContest: "8"
HomeTeamTotalCornersIntobox: "1"
HomeTeamTotalCross: "7"
HomeTeamTotalCrossNocorner: "6"
HomeTeamTotalFlickOn: "5"
HomeTeamTotalFwdZonePass: "89"
HomeTeamTotalLaunches: "8"
HomeTeamTotalLayoffs: "9"
HomeTeamTotalLongBalls: "16"
HomeTeamTotalPass: "152"
HomeTeamTotalScoringAtt: "4"
HomeTeamTotalTackle: "11"
HomeTeamTotalThroughBall: "3"
HomeTeamTotalThrows: "15"
HomeTeamTotalYelCard: "2"
HomeTeamTouches: "262"
HomeTeamWonCorners: "1"
HomeTeamWonTackle: "8"
MatchAttendance: "55359"
MatchDate: "20100706T193000+0100"
MatchPeriod: "FirstHalf"
MatchTime: "41"
MatchType: "Cup"
MatchWinner: "Spain"
Referee: "Ravshan Irmatov"
ResultType: "NormalResult"
Venue: "Green Point Stadium"
*/
var Replay={
	initialize:function() {
		var oConnection = kwwika.Service.connect();
		var oSubscription = oConnection.subscribe("/OPTA/WC2010/REPLAY", {
			topicUpdated:function(oSub, d){
				$$('#home h1')[0].update(d.HomeTeam);
				$$('#away h1')[0].update(d.AwayTeam);
				
				$$('#home h2')[0].update(d.HomeTeamScore);
				$$('#away h2')[0].update(d.AwayTeamScore);
				
				
				Replay.passes(d);
			},
			topicError:function(oSub, sError){ return; }
		});
	},
	
	passes:function(d) {
		$$('#passes li')[0].update("<strong>"+d.HomeTeam+"</strong>: "+d.HomeTeamAccuratePass);
		$$('#passes li')[1].update("<strong>"+d.AwayTeam+"</strong>: "+d.AwayTeamAccuratePass);
	}
};

Event.observe(window, "load", function() {
	Replay.initialize();
});